apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod  #name for the pod 
spec:
  containers:
  - name: my-cont   #name for the container 
    image: nginx:latest
    ports:
    - containerPort: 80

# kubectl apply -f pod.yaml
# kubectl get pod nginx-pod -o yaml / kubectl get pod -o wide
