apiVersion: v1
kind: Pod
metadata:
  name: nginx  #name for the pod 
spec:
  containers:
  - name: nginx   #name for the container 
    image: nginx:1.14.2
    ports:
    - containerPort: 80

# kubectl apply -f pod.yaml
# kubectl get pod nginx -o yaml / kubectl get pod -o wide
